# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, "8.0"
use_frameworks!

## NetWork & JsonMap
pod 'Alamofire', '~> 1.3'
pod 'SwiftyJSON', '~> 2.2.1'
pod 'AlamofireObjectMapper', '~> 0.7'
pod 'Moya'

## UI
pod 'PullToRefresher', '~> 1.0'
pod 'SnapKit'

##Else
pod 'Dollar'
